# Generated by Django 2.2.3 on 2020-07-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('weekname', models.CharField(max_length=30)),
                ('t1', models.CharField(max_length=30)),
                ('t2', models.CharField(max_length=30)),
                ('t3', models.CharField(max_length=30)),
                ('t4', models.CharField(max_length=30)),
                ('t5', models.CharField(max_length=30)),
                ('t6', models.CharField(max_length=30)),
                ('t7', models.CharField(max_length=30)),
                ('t8', models.CharField(max_length=30)),
            ],
        ),
    ]
